

<!DOCTYPE html>
<html lang="es">
	<head>
	  <meta charset="UTF-8" content="text/html">
		<title> Portal </title>
	  	<link rel="stylesheet" href="css/bootstrap.min.css">
	  	<link rel="stylesheet" href="css/estilos.css">

        <link href="css/ui-darkness/jquery-ui-1.8.16.custom.css" rel="stylesheet" media="screen">
	  	<script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.8.16.custom.min.js"></script>
		<script type="text/javascript" src="js/jquery-validation-1.9.0/jquery.validate.min.js"></script>
		<script type="text/javascript" src="js/jquery-validation-1.9.0/lib/jquery.metadata.js"></script>
		
				

	</head>
	
	<body style="background-color:#B8EBEE">