<!DOCTYPE html>
<html lang="es">
	<head>
	<meta http-equiv="Content-Type" content="text/html charset=utf-8"/>
	
		<title> Portal </title>
	  	<link rel="stylesheet" href="css/bootstrap.min.css">
	  	
	  	<script src="alertas/dist/sweetalert.min.js"></script>
		<link rel="stylesheet" type="text/css" href="alertas/dist/sweetalert.css">	

        <link href="css/ui-darkness/jquery-ui-1.8.16.custom.css" rel="stylesheet" media="screen">
	  	<script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
		<script type="text/javascript" src="js/jquery-ui-1.8.16.custom.min.js"></script>
		<script type="text/javascript" src="js/jquery-validation-1.9.0/jquery.validate.min.js"></script>
		<script type="text/javascript" src="js/jquery-validation-1.9.0/lib/jquery.metadata.js"></script>
		
	    <style type="text/css">
	    	#footer {
			  position: absolute;
			  bottom: 0;
			  width: 100%;
			  /* Set the fixed height of the footer here */
			  height: 280px;
			  background: 
			  /* color overlay */ 
			    linear-gradient(
			      rgba(240, 212, 0, 0.45), 
			      rgba(0, 0, 0, 0.45)
			    ),
			    /* image to overlay */
			    url(http://images.cdn.fotopedia.com/_avPIZmqM3w-7z161LH_268-hd.jpg);
			}
	    </style>

	</head>
	
	<body style="background-color:#B8EBEE">